// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteVideo(path: string): $CancellablePromise<void> {
    return $Call.ByID(4154542665, path);
}

export function DirectoryVideos(path: string): $CancellablePromise<$models.MediaItem[]> {
    return $Call.ByID(3847526080, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ExtractContactSheet(path: string, frameCount: number, imageWidth: number): $CancellablePromise<string> {
    return $Call.ByID(2202839665, path, frameCount, imageWidth);
}

export function MarkPlayed(path: string): $CancellablePromise<void> {
    return $Call.ByID(180312699, path);
}

export function OpenSubtitle(): $CancellablePromise<$models.MediaItem> {
    return $Call.ByID(614166045).then(($result: any) => {
        return $$createType0($result);
    });
}

export function OpenVideos(): $CancellablePromise<$models.MediaItem[]> {
    return $Call.ByID(3007781241).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ProbeMedia(path: string): $CancellablePromise<$models.MediaInfo> {
    return $Call.ByID(614641911, path).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RecentVideos(): $CancellablePromise<$models.MediaItem[]> {
    return $Call.ByID(1995266018).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetLocale(locale: string): $CancellablePromise<string> {
    return $Call.ByID(2991417501, locale);
}

export function SplitVideo(path: string, seconds: number): $CancellablePromise<$models.SplitResult> {
    return $Call.ByID(2078186822, path, seconds).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MediaItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.MediaInfo.createFrom;
const $$createType3 = $models.SplitResult.createFrom;
