// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearThumbnailCache(): $CancellablePromise<void> {
    return $Call.ByID(3775367792);
}

export function DeleteVideo(path: string): $CancellablePromise<void> {
    return $Call.ByID(4154542665, path);
}

export function DirectoryVideos(path: string): $CancellablePromise<$models.MediaItem[]> {
    return $Call.ByID(3847526080, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ExtractContactSheet(path: string, frameCount: number, imageWidth: number): $CancellablePromise<string> {
    return $Call.ByID(2202839665, path, frameCount, imageWidth);
}

export function GenerateThumbnails(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(353131923, paths);
}

export function GetLocalization(locale: string): $CancellablePromise<$models.LocalizationPayload> {
    return $Call.ByID(1859751638, locale).then(($result: any) => {
        return $$createType2($result);
    });
}

export function MarkPlayed(path: string): $CancellablePromise<void> {
    return $Call.ByID(180312699, path);
}

export function OpenSubtitle(): $CancellablePromise<$models.MediaItem> {
    return $Call.ByID(614166045).then(($result: any) => {
        return $$createType0($result);
    });
}

export function OpenVideos(): $CancellablePromise<$models.MediaItem[]> {
    return $Call.ByID(3007781241).then(($result: any) => {
        return $$createType1($result);
    });
}

export function PauseThumbnailGeneration(): $CancellablePromise<void> {
    return $Call.ByID(3891602989);
}

export function ProbeMedia(path: string): $CancellablePromise<$models.MediaInfo> {
    return $Call.ByID(614641911, path).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RecentVideos(): $CancellablePromise<$models.MediaItem[]> {
    return $Call.ByID(1995266018).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ResumeThumbnailGeneration(): $CancellablePromise<void> {
    return $Call.ByID(1934657156);
}

export function SplitVideo(path: string, seconds: number): $CancellablePromise<$models.SplitResult> {
    return $Call.ByID(2078186822, path, seconds).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SplitVideoAtMarkers(path: string, seconds: number[]): $CancellablePromise<$models.MultiSplitResult> {
    return $Call.ByID(1021854198, path, seconds).then(($result: any) => {
        return $$createType5($result);
    });
}

export function StopThumbnailGeneration(): $CancellablePromise<void> {
    return $Call.ByID(1333779077);
}

export function ThumbnailGenerationStatus(): $CancellablePromise<$models.ThumbnailProgress> {
    return $Call.ByID(1427037375).then(($result: any) => {
        return $$createType6($result);
    });
}

export function TranscodeOptions(path: string): $CancellablePromise<$models.TranscodeOption[]> {
    return $Call.ByID(3683531566, path).then(($result: any) => {
        return $$createType8($result);
    });
}

export function TranscodeVideo(path: string, optionID: string): $CancellablePromise<$models.TranscodeResult> {
    return $Call.ByID(2627797619, path, optionID).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MediaItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.LocalizationPayload.createFrom;
const $$createType3 = $models.MediaInfo.createFrom;
const $$createType4 = $models.SplitResult.createFrom;
const $$createType5 = $models.MultiSplitResult.createFrom;
const $$createType6 = $models.ThumbnailProgress.createFrom;
const $$createType7 = $models.TranscodeOption.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.TranscodeResult.createFrom;
