// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LocaleOption {
    "code": string;
    "label": string;

    /** Creates a new LocaleOption instance. */
    constructor($$source: Partial<LocaleOption> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocaleOption instance from a string or object.
     */
    static createFrom($$source: any = {}): LocaleOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocaleOption($$parsedSource as Partial<LocaleOption>);
    }
}

export class LocalizationPayload {
    "locale": string;
    "defaultLocale": string;
    "locales": LocaleOption[];
    "messages": { [_ in string]?: string };

    /** Creates a new LocalizationPayload instance. */
    constructor($$source: Partial<LocalizationPayload> = {}) {
        if (!("locale" in $$source)) {
            this["locale"] = "";
        }
        if (!("defaultLocale" in $$source)) {
            this["defaultLocale"] = "";
        }
        if (!("locales" in $$source)) {
            this["locales"] = [];
        }
        if (!("messages" in $$source)) {
            this["messages"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalizationPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalizationPayload {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("locales" in $$parsedSource) {
            $$parsedSource["locales"] = $$createField2_0($$parsedSource["locales"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField3_0($$parsedSource["messages"]);
        }
        return new LocalizationPayload($$parsedSource as Partial<LocalizationPayload>);
    }
}

export class MediaInfo {
    "container": string;
    "videoCodec": string;
    "audioCodec": string;
    "width": number;
    "height": number;
    "fps": string;
    "duration": number;
    "size": number;
    "probeAvailable": boolean;

    /** Creates a new MediaInfo instance. */
    constructor($$source: Partial<MediaInfo> = {}) {
        if (!("container" in $$source)) {
            this["container"] = "";
        }
        if (!("videoCodec" in $$source)) {
            this["videoCodec"] = "";
        }
        if (!("audioCodec" in $$source)) {
            this["audioCodec"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("fps" in $$source)) {
            this["fps"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("probeAvailable" in $$source)) {
            this["probeAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaInfo($$parsedSource as Partial<MediaInfo>);
    }
}

export class MediaItem {
    "name": string;
    "path": string;
    "url": string;
    "thumbnailUrl": string;
    "kind": string;

    /** Creates a new MediaItem instance. */
    constructor($$source: Partial<MediaItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("thumbnailUrl" in $$source)) {
            this["thumbnailUrl"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaItem($$parsedSource as Partial<MediaItem>);
    }
}

export class SplitResult {
    "firstPath": string;
    "secondPath": string;
    "splitTime": number;

    /** Creates a new SplitResult instance. */
    constructor($$source: Partial<SplitResult> = {}) {
        if (!("firstPath" in $$source)) {
            this["firstPath"] = "";
        }
        if (!("secondPath" in $$source)) {
            this["secondPath"] = "";
        }
        if (!("splitTime" in $$source)) {
            this["splitTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SplitResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SplitResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SplitResult($$parsedSource as Partial<SplitResult>);
    }
}

// Private type creation functions
const $$createType0 = LocaleOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
