// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class MediaInfo {
    "container": string;
    "videoCodec": string;
    "audioCodec": string;
    "width": number;
    "height": number;
    "fps": string;
    "duration": number;
    "size": number;
    "probeAvailable": boolean;

    /** Creates a new MediaInfo instance. */
    constructor($$source: Partial<MediaInfo> = {}) {
        if (!("container" in $$source)) {
            this["container"] = "";
        }
        if (!("videoCodec" in $$source)) {
            this["videoCodec"] = "";
        }
        if (!("audioCodec" in $$source)) {
            this["audioCodec"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("fps" in $$source)) {
            this["fps"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("probeAvailable" in $$source)) {
            this["probeAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaInfo($$parsedSource as Partial<MediaInfo>);
    }
}

export class MediaItem {
    "name": string;
    "path": string;
    "url": string;
    "thumbnailUrl": string;
    "kind": string;

    /** Creates a new MediaItem instance. */
    constructor($$source: Partial<MediaItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("thumbnailUrl" in $$source)) {
            this["thumbnailUrl"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaItem($$parsedSource as Partial<MediaItem>);
    }
}

export class SplitResult {
    "firstPath": string;
    "secondPath": string;
    "splitTime": number;

    /** Creates a new SplitResult instance. */
    constructor($$source: Partial<SplitResult> = {}) {
        if (!("firstPath" in $$source)) {
            this["firstPath"] = "";
        }
        if (!("secondPath" in $$source)) {
            this["secondPath"] = "";
        }
        if (!("splitTime" in $$source)) {
            this["splitTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SplitResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SplitResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SplitResult($$parsedSource as Partial<SplitResult>);
    }
}
