// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenSubtitle() {
  return window['go']['main']['App']['OpenSubtitle']();
}

export function OpenVideos() {
  return window['go']['main']['App']['OpenVideos']();
}
