// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenSubtitle():Promise<main.MediaItem>;

export function OpenVideos():Promise<Array<main.MediaItem>>;
